robot:
  # Publish all joint states ----------------------------------
  joint_state_controller:
    ros__parameters:
      type: joint_state_controller/JointStateController
      publish_rate: 50  
      
  